[package]
name = "pm-licht"
version = "0.1.0"
edition = "2021"

[dependencies]
rs_ws281x = "0.5"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
